### ISSUE TITLE
Example incorrect

### ISSUE THREAD

**Issue by nappa85** [sile/rustracing_jaeger#1]
Sorry to bother you, I'm just a newbie about both Rust and OpenTracing, but the correct command to launch jaeger's container is:
docker run -d -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p5775:5775/udp -p6831:6831/udp -p6832:6832/udp -p5778:5778 -p16686:16686 -p14268:14268 -p9411:9411 jaegertracing/all-in-one:latest

Using the command written on your example ends on a non-collecting jaeger.
Sorry again,
best regards

**Comment by sile** [comment]
Hmm, I tried running the example code with the jaeger that started by the above docker command, but it worked correctly in my environment.

**Comment by nappa85** [comment]
The one I wrote on my report is the ufficial version as found on jaeger documentation (https://jaeger.readthedocs.io/en/latest/getting_started/), your version is clearly missing parameters:
docker run -d -p6831:6831/udp -p6832:6832/udp -p16686:16686 jaegertracing/all-in-one:latest

**Comment by sile** [comment]
I understand what you mean.

Indeed, my example uses a docker command that is different from what is written in the official document.
But it is sufficient for the example, and I like to use simple command rather than unnecessary long command for examples.

So, as an alternative, I'd like to add the following notes, what do you think?

```
# Run jaeger in background
#
# Note that the following command only specifies the minimum options required to run this example.
# For the complete command, please refer to the Jaeger's official documentation.
# (e.g., https://jaeger.readthedocs.io/en/latest/getting_started/)
#
$ docker run -d -p6831:6831/udp -p6832:6832/udp -p16686:16686 jaegertracing/all-in-one:latest

# Report example spans
$ cargo run --example report

# View spans
$ firefox http://localhost:16686/
```
