### ISSUE TITLE
Allow connecting to non-local agents

### ISSUE THREAD

**Issue by matevz** [sile/rustracing_jaeger#10]
Currently, only UDP connections to IP addresses bound to loopback interface are supported, because `bind()` is called with address `127.0.0.1:0` here: https://github.com/sile/rustracing_jaeger/blob/master/src/reporter.rs#L118

Consequently, `reporter.set_agent_addr()` seems pretty useless since your can only set a different port. To allow connecting to agents on other network interfaces with external IP addresses, you should bind to `0.0.0.0:0`.

**Comment by sile** [comment]
Thank you for pointing it out.
I fixed this problem at the commit https://github.com/sile/rustracing_jaeger/commit/62f0ebd877cb9d32fe008e4631d9b46511af6736.

**Comment by matevz** [comment]
works, thanks.
