### ISSUE TITLE
Constructing TraceId from String

### ISSUE THREAD

**Issue by nevi-me** [sile/rustracing_jaeger#16]
How can I generate a 128-bit `TraceId` from a string like `129fb82c233ed2ae7782257c92481779%3A7782257c92481779%3A0%3A1`? The `TraceId` accepts a high and low number, but I'm not sure of how to extract those in Rust.

**Comment by nevi-me** [comment]
Found it, I can `"trace-32-char".parse<TraceId>()?`

**Comment by sile** [comment]
:+1:
