### ISSUE TITLE
What is the expected way of using this library across threads?

### ISSUE THREAD

**Issue by thedodd** [sile/rustracing_jaeger#2]
For example, given a gRPC server using a thread based concurrency model, is it expected that each request (being handled on a separate thread) would instantiate a new `Tracer::new(AllSampler)`?

I would prefer to be able to inject the tracer as a middleware, and then clone it per thread or something of the sort.

Any ideas? I may be totally missing something as well.

**Comment by sile** [comment]
[Tracer](https://docs.rs/rustracing_jaeger/0.1.4/rustracing_jaeger/struct.Tracer.html) implements `Clone` and ` Send` traits, so it is possible to clone a `Tracer` for multiple threads as the following code:

```rust
let (tracer, _) = Tracer::new(AllSampler); 
for _ in 0..10 {
    let tracer = tracer.clone();  
    std::thread::spawn(move || {
        let span = tracer.span("foo").start();
        // Do something
    });
}
```

**Comment by thedodd** [comment]
Ah, yes. The main thing I was looking for was the `Sync` bit. I've worked around this constraint by wrapping the `Tracer` in a pointer which is itself sync, and passing that pointer to the various threads. When the pointer is dereferenced, it clones the underlying `Tracer` for thread local usage. Seems to be working quite well.

Traces are coming through without issue.

**Comment by sile** [comment]
I'm glad the problem was solved.
