### ISSUE TITLE
Bind to localhost instead of INADDR_ANY for reporter UDP socket creation

### ISSUE THREAD

**Issue by anita-tenjarla** [sile/rustracing_jaeger#25]
In https://github.com/sile/rustracing_jaeger/blob/eca08a5f2ff82fa4cd7887591dc2f68ecf143ad9/src/reporter.rs#L164-L173, we bind to all addresses (::0 and 0.0.0.0) to create an ephemeral port for reporting. Binding to INADDR_ANY for UDP ports increases the attack surface for potential denial of service since INADDR_ANY UDP ports will always accept all traffic that comes its way.

A proposed fix is to only bind to localhost for both ipv4 and ipv6. As far as I can tell, this won't change existing functionality & will still pass tests. This will ultimately just be two lines changed: 
src/reporter.rs line 167: `SocketAddr::new(IpAddr::V6(Ipv6Addr::new(0, 0, 0, 0, 0, 0, 0, 1)), 0)`
src/reporter.rs line 169: `SocketAddr::new(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)), 0)`

I understand that since we're using an ephemeral port the risk isn't quite as big for DoS as a privileged port, however we're doing some network cleanup and found that a few of our applications unnecessarily use INADDR_ANY, so making this fix would clean up a lot of these patterns.

**Comment by sile** [comment]
Hi, sorry for the delayed response and thank you for creating this issue.

Your opinion seems reasonable but using INADDR_ANY is a desired feature by a user (see https://github.com/sile/rustracing_jaeger/issues/10). So I'd like to "change the default to `SocketAddr::new(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)), 0)`" as you suggested, and provides a new option to control whether to use INADDR_ANY.
What do you think of it?

**Comment by anita-tenjarla** [comment]
I think that's a great idea! So what's the next steps here, would you prefer to open a PR or should I?

**Comment by sile** [comment]
Thank you for your reply! If you can wait until this weekend, I'll create the PR. Of course, your contribution is very welcomed if you're interested in doing that.

**Comment by anita-tenjarla** [comment]
Oops! Sorry I missed this. If it's alright with you, I'll just wait til this weekend for your PR (or whenever you get a chance).

**Comment by sile** [comment]
Okay. No problem! I'll create the PR.

**Comment by sile** [comment]
Created https://github.com/sile/rustracing_jaeger/pull/26.
Instead of adding an option, I introduced methods to change the reporter's biding address.

**Comment by anita-tenjarla** [comment]
Looks great, thank you! I'll close this issue once PR is merged.
