### ISSUE TITLE
Make it possible to retrieve `flags`

### ISSUE THREAD

**Issue by jyn514** [sile/rustracing_jaeger#30]
Right now, `SpanContextState::flags()` is crate-private, making it impossible to retrieve the flags (e.g. for serialization to another service). It would be nice for it to be public instead; I'm having to use `opentelemetry-jaeger` instead in the meantime.

**Comment by sile** [comment]
It sounds nice.
I'll be busy for a while but I can review the PR if you (or someone) create that.
