### ISSUE TITLE
Running into an error when using an alternative SocketAddr.

### ISSUE THREAD

**Issue by thedodd** [sile/rustracing_jaeger#5]
When using `set_agent_addr` using both the compact and binary reporter, the system seems to be failing.

I am using the all-in-one agent, running in docker. The all-in-one and the service which is generating this stacktrace, are both on the same docker network, and can route to each other. The all-in-one is configured as described in the jaeger docs.

```
thread '<unnamed>' panicked at 'Failed to send trace.: Error(TrackableError { kind: Other,
cause: Some(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }),
history: History([Track(Location { module_path: "rustracing_jaeger::reporter",
file: "/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rustracing_jaeger-0.1.4/src/reporter.rs",
line: 159, message: "" }), Track(Location { module_path: "rustracing_jaeger::reporter",
file: "/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rustracing_jaeger-0.1.4/src/reporter.rs",
line: 102, message: "" })]) })', libcore/result.rs:945:5
stack backtrace:
   0:     0x559a3940f9b3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h8b81594645a24a27
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x559a39409ce4 - std::sys_common::backtrace::_print::h9bc07d566820e560
                               at libstd/sys_common/backtrace.rs:71
   2:     0x559a3940e3ed - std::panicking::default_hook::{{closure}}::h8061f115b067df97
                               at libstd/sys_common/backtrace.rs:59
                               at libstd/panicking.rs:380
   3:     0x559a3940e0f2 - std::panicking::default_hook::hd067eb3eb1a62c48
                               at libstd/panicking.rs:396
   4:     0x559a3940e860 - std::panicking::rust_panic_with_hook::h45183031f05ee04c
                               at libstd/panicking.rs:576
   5:     0x559a3940e6ae - std::panicking::begin_panic::h9ee67e5b096c21ab
                               at libstd/panicking.rs:537
   6:     0x559a3940e619 - std::panicking::begin_panic_fmt::he72e33953442af8b
                               at libstd/panicking.rs:521
   7:     0x559a3940e5a2 - rust_begin_unwind
                               at libstd/panicking.rs:497
   8:     0x559a39453fb0 - core::panicking::panic_fmt::hc4dea8542bac164c
                               at libcore/panicking.rs:71
   9:     0x559a38dbf5a7 - core::result::unwrap_failed::he9a5bc32c056badf
                               at /checkout/src/libcore/macros.rs:23
  10:     0x559a38dbd6d0 - <core::result::Result<T, E>>::expect::h84035c0c3a5db2a4
                               at /checkout/src/libcore/result.rs:809
  11:     0x559a38dc1824 - gateway_service::trace_emitter::h4616a61519895d37
                               at src/bin/gateway-service.rs:82
  12:     0x559a38e06e1b - gateway_service::main::{{closure}}::h34a8ef0f05e0c94d
                               at src/bin/gateway-service.rs:55
  13:     0x559a38e17f1b - std::sys_common::backtrace::__rust_begin_short_backtrace::h1417833fefa4bd66
                               at /checkout/src/libstd/sys_common/backtrace.rs:136
  14:     0x559a38dc39c5 - std::thread::Builder::spawn::{{closure}}::{{closure}}::h408105891343468a
                               at /checkout/src/libstd/thread/mod.rs:406
  15:     0x559a38e06fc1 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc17189e1209a3c76
                               at /checkout/src/libstd/panic.rs:293
  16:     0x559a38de8591 - std::panicking::try::do_call::h96cb67a132d1ade4
                               at /checkout/src/libstd/panicking.rs:479
  17:     0x559a3941994e - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  18:     0x559a38de825c - std::panicking::try::hc3afa170fb79ed25
                               at /checkout/src/libstd/panicking.rs:458
  19:     0x559a38e070f3 - std::panic::catch_unwind::had632088dcfd6bc2
                               at /checkout/src/libstd/panic.rs:358
  20:     0x559a38dc351a - std::thread::Builder::spawn::{{closure}}::hd348c61cc1485b06
                               at /checkout/src/libstd/thread/mod.rs:405
  21:     0x559a38dc3a15 - <F as alloc::boxed::FnBox<A>>::call_box::hc6c90317650b9686
                               at /checkout/src/liballoc/boxed.rs:788
  22:     0x559a394118bb - std::sys::unix::thread::Thread::new::thread_start::hdd261da30813e955
                               at /checkout/src/liballoc/boxed.rs:798
                               at libstd/sys_common/thread.rs:24
                               at libstd/sys/unix/thread.rs:90
  23:     0x7f0a7aa18493 - start_thread
  24:     0x7f0a7a543afe - __clone
  25:                0x0 - <unknown>
```

Any ideas?

**Comment by sile** [comment]
The error seems to be occurring where data is being sent using the standard `UdpSocket` ([report.rs#L161](https://github.com/sile/rustracing_jaeger/blob/0.1.4/src/reporter.rs#L161)).

In the documentation of [UdpSocket::send_to()](https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.send_to), it says "This will return an error when the IP version of the local socket does not match that returned from `ToSocketAddrs`", which may be the cause.

`JaegerReport` alwasy binds to an IP address which version is version 4 ([reporter#L122](https://github.com/sile/rustracing_jaeger/blob/0.1.4/src/reporter.rs#L122)). If the version of your specified address was 6, the error can happen.

**Comment by thedodd** [comment]
I will continue to investigate this further. I am definitely not attempting to use IPv6, but I will dig into the referenced code and see if I can resolve the issue.

**Comment by sile** [comment]
> I am definitely not attempting to use IPv6

Hmm...
If you could tell me the detailed commands (and code) to reproduce the error, I will also investigate the cause.

**Comment by thedodd** [comment]
This is an abridged version, but is accurate in terms of what is finally fed into `set_agent_addr`. The logged addr that it ends up passing in is: `172.24.0.2:6831`.
```rust
let tracing_url = String::from("tracing:6831");
let mut reporter = JaegerCompactReporter::new("gateway-service").unwrap();
if let Ok(mut addrs) = tracing_url.to_socket_addrs() {
    if let Some(addr) = addrs.next() {
        info!(log, "Setting tracing endpoint to: {}", addr);
        reporter.set_agent_addr(addr);
    }
}
```

A few notes after reviewing the [send_to](https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.send_to) docs:
- I have the all-in-one jaeger container running in a separate container, and it is resolvable at the DNS name `tracing`. Listening on port `6831`. It successfully resolves to the IP address mentioned above.
- In the container which is attempting to emit events to it, I have done absolutely nothing other than feed in `tracing:6831` as the endpoint which it needs to communicate with.
- in a non-local environment, I use k8s and will have an agent in the pod of each service, and that works as expected (I don't supply a custom endpoint in those cases).

Do I need to open up any other sockets from the container which is attempting to emit events?

According to the docs for `send_to` with the following signature: `pub fn send_to<A: ToSocketAddrs>(&self, buf: &[u8], addr: A) -> Result<usize>`:

> It is possible for addr to yield multiple addresses, but send_to will only send data to the first address yielded by addr.
> This will return an error when the IP version of the local socket does not match that returned from ToSocketAddrs.

So, I wonder if it is attempting to look up additional IPs for the given IPv4 and then potentially getting an IPv6, and then bombing out ... just a thought.

**Comment by sile** [comment]
Thank you for your information.
I tried it a bit but eventually I could not reproduce the error in my environment.
Since the issue https://github.com/moby/moby/issues/29992 seems to be similar, there may be a possibility that it is a problem of Docker...?

**Comment by sile** [comment]
If the destination address is IPv6, it will cause an error. But it seems to be different from the above error.

```rust
 use std::net::{SocketAddr, UdpSocket};

 fn main() {
     // src=IPv4, dst=IPv4 => OK
     let udp_ipv4 = UdpSocket::bind("127.0.0.1:0".parse::<SocketAddr>().unwrap()).unwrap();
     udp_ipv4
         .send_to(&[], "127.0.0.1:3000".parse::<SocketAddr>().unwrap())
         .expect("OK");

     // src=IPv6, dst=IPv6 => OK
     let udp_ipv6 = UdpSocket::bind("[::1]:0".parse::<SocketAddr>().unwrap()).unwrap();
     udp_ipv6
         .send_to(&[], "[::1]:3000".parse::<SocketAddr>().unwrap())
         .expect("OK");

     // src=IPv4, dst=IPv6 => Error (but not "Invalid argument" error)
     let error = udp_ipv4
         .send_to(&[], "[::1]:3000".parse::<SocketAddr>().unwrap())
         .expect_err("Error");

     // [OUTPUT] Address family not supported by protocol (os error 97)
     println!("{}", error);
 }
```

**Comment by thedodd** [comment]
Yea, not entirely sure what the deal is. I will need to come back to this at some point in the future when I have a bit more time to look into it.

**Comment by thedodd** [comment]
No longer an issue for me. Using a different infrastructure pattern these days. No need for the alternative addr.

**Comment by jsenon** [comment]
I've same issue. Have you resolved it?

**Comment by jsenon** [comment]
Any change to have an implementation over TCP instead of UDP with jaeger collector on port 9411?

**Comment by jongiddy** [comment]
I found this problem while using Docker Compose to test with the all-in-one agent. Eventually I realized that, as well as calling `JaegerReporter::set_agent_addr` with the Jaeger container IP address, I needed to call `JaegerReporter::set_reporter_addr` with the IP address of the client container and port 0.
