### ISSUE TITLE
Allow generating span from known TraceId

### ISSUE THREAD

**Issue by stearnsc** [sile/rustracing_jaeger#7]
I'm instrumenting a system that's already using trace IDs, and would like a clean way to use that existing trace ID to generate a span (right now only way I'm aware of is to generate a fake header string and use SpanContextState's FromStr impl).

In general this would allow broader support of custom carrier formats (even if it's just custom header names).

From what I can see, the easiest way to do that would be to make SpanContextState::with_trace_id public, but there might be better ways to do it in order to keep the api clean.

**Comment by sile** [comment]
It seems good feature.
I think that exporting `SpanContextState::with_trace_id` is not bad idea, but I will also consider other ways a little.

**Comment by sile** [comment]
I added [SpanContextStateBuilder](https://docs.rs/rustracing_jaeger/0.1.6/rustracing_jaeger/span/struct.SpanContextStateBuilder.html) at the version `0.1.6` for the purpose.

**Comment by stearnsc** [comment]
Updated to 0.1.6 and looks great, thanks!

**Comment by sile** [comment]
👍
